### ISSUE TITLE
"No tag found" error when installing library with bower

### ISSUE THREAD

**Issue by narqo** [yiminghe/simulate-dom-event#1]
I want to use bower to install `simulate-dom-event` as my project dev-dependency, but since there is no any version tags in the repo, bower installation failed with: 

```
"bower simulate-dom-event#^1.0.2     ENORESTARGET No tag found that was able to satisfy ^1.0.2

Additional error details:
No versions found in git://github.com/yiminghe/simulate-dom-event.git"
```

Here is my `bower.json`:

``` json
{
  "name": "bem-pr",
  "devDependencies": {
    "simulate-dom-event": "^1.0.2"
  }
}
```

I can use "*" (any version) instead of exact version range, but I strongly believe it's a bad practice.

Please add appropriate tags to the repo.

**Comment by yiminghe** [comment]
Added. Thanks, I personally recommend using npm in front-end development.
